### ISSUE TITLE
Fix Layout Bugs

### ISSUE THREAD

**Issue by roberthd008** [r2luna/gmless#60]
I'm making this is story for the next sprint. This is is just to go through and make sure everything looks right visually from any browser or OS.

**Comment by ColtonNash** [comment]
Awesome that's a great idea.

Sent from my iPhone

On Jul 12, 2017, at 3:21 PM, roberthd008 <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm making this is story for the next sprint. This is is just to go through and make sure everything looks right visually from any browser or OS.
